### auth.http

@baseUrl = http://localhost:4000
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

### ================== RUTAS SIN AUTENTICACIÓN ==================

### Obtener todos los usuarios
GET {{baseUrl}}/api/users

### Registrar un nuevo usuario
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "username": "jhon",
  "email": "jhon@gmail.com",
  "password": "jhon123",
  "is_active": "ACTIVE",
  "avatar": "avatar.jpg"
}

### Iniciar sesión
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin123"
}

### ================== RUTAS CON AUTENTICACIÓN ==================